# Server-side configuration
server:

  # Server listening address
  listen: 127.0.0.1:18888

  # Forwarding port pairs from server to client
  forwarding:
    - listen: 127.0.0.1:2000 # Server-side UDP listening address
      target: 127.0.0.1:2001 # Client-side UDP connecting target
    - listen: 127.0.0.1:3000
      target: 127.0.0.1:3001

# Client-size configuration
client:

  # Client connecting target
  connect: localhost:18888

  # Forwarding port pairs from client to server
  forwarding:
    - listen: 127.0.0.1:6001 # Client-side UDP listening address
      target: 127.0.0.1:6000 # Server-side UDP connecting target
    - listen: 127.0.0.1:7001
      target: 127.0.0.1:7000
