balancers:
  - ip: 10.0.0.100
    port: 8080
    targets:
      - ip: 10.0.1.200
        port: 8080
        weight: 100
      - ip: 10.0.2.200
        port: 8080
        weight: 100
      - ip: 10.0.3.200
        port: 8080
        weight: 100
