http:
  - listen:
      tcp:
        ports: [8080]
      tls:
        ports: [8443]
        certificates:
          cert: secret/server-cert.pem
          key: secret/server-key.pem
    services:
      foo:
        type: files
        path: www
      bar:
        type: proxy
        protocol: http
        targets:
          - 127.0.0.1:9000
          - 127.0.0.1:9001
          - 127.0.0.1:9002
        rewrite:
          pattern: ^/api
          replace: ""
    routes:
      /api/*: bar
      /*: foo
tcp:
  - listen: [8008]
    targets:
      - 127.0.0.1:9000
      - 127.0.0.1:9001
      - 127.0.0.1:9002
